### ISSUE TITLE
Investigate Py3K support

### ISSUE THREAD

**Issue by xiongchiamiov** [xiongchiamiov/ghgrep#2]
It'd be good to support Python 3.x, since, well, it's been out for a while.  A long while.

[Tox](http://codespeak.net/tox/) should help, as well as various other resources found on http://getpython3.com/ .

**Comment by xiongchiamiov** [comment]
I'm having issues even getting the dependencies installed:

```
(env-py3k)┌─[pearson@geror] - [~/Documents/ghgrep] - [Mon May 27, 11:28]
└─[$]> pip install -r requirements.txt
Downloading/unpacking docopt==0.6.1 (from -r requirements.txt (line 1))
  Downloading docopt-0.6.1.tar.gz
  Running setup.py egg_info for package docopt

Downloading/unpacking envoy==0.0.2 (from -r requirements.txt (line 2))
  Downloading envoy-0.0.2.tar.gz
  Running setup.py egg_info for package envoy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/pearson/Documents/ghgrep/env-py3k/build/envoy/setup.py", line 6, in <module>
        import envoy
      File "./envoy/__init__.py", line 1, in <module>
        from core import *
    ImportError: No module named 'core'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/pearson/Documents/ghgrep/env-py3k/build/envoy/setup.py", line 6, in <module>

    import envoy

  File "./envoy/__init__.py", line 1, in <module>

    from core import *

ImportError: No module named 'core'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/pearson/Documents/ghgrep/env-py3k/build/envoy
Storing complete log in /Users/pearson/.pip/pip.log
```

Which is probably the fault of my toolchain.
